version: '2'
services:
    invoices-app:
        image: invoices
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://invoices-postgresql:5432/Invoices
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    invoices-postgresql:
        extends:
            file: postgresql.yml
            service: invoices-postgresql
